### ISSUE TITLE
 executable file not found in $PATH after running docker

### ISSUE THREAD

**Issue by jengeb** [pelias/interpolation#117]
I tried to create `street.db` from polyline data using docker but received this error message. 

```
$ cat /data/brandenburg.polylines | docker run -i -v /data:/data pelias/interpolation polyline /data/street.db

container_linux.go:247: starting container process caused "exec: \"polyline\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"polyline\": executable file not found in $PATH".
ERRO[0000] error getting events from daemon: net/http: request canceled 
```

Do you have a hint how to fix this? Are there any parameters or configurations that need to be passed? Or is it maybe a docker issue?

**Comment by missinglink** [comment]
hmm... the `ENTRYPOINT` command seems to have been removed in https://github.com/pelias/interpolation/commit/1ede4e276e9a8b60273385837f099b11a8672377#diff-3254677a7917c6c01f55212f86c57fbf

I'll fix it

**Comment by missinglink** [comment]
PR opened, an interim solution is to add the `--entrypoint='./interpolate'` to your `docker run` commands (not tested).

**Comment by jengeb** [comment]
Thank you! Now it is working perfectly.

**Comment by missinglink** [comment]
The fix for this issue should now be available on dockerhub, please pull the most recent image.
