### ISSUE TITLE
investigate - willow ave, hoboken

### ISSUE THREAD

**Issue by dianashk** [pelias/interpolation#13]
Search for this address: `1601 Willow Avenue, Hoboken, NJ` and then click on the `Willow Avenue`. You can see at either end of the street there are far reaching offshoots.

<img width="586" alt="screen shot 2016-10-17 at 1 06 42 pm" src="https://cloud.githubusercontent.com/assets/5446511/19447242/98101916-946a-11e6-961f-b9bd01a639ce.png">

**Comment by missinglink** [comment]
a cursory glance at this shows that one a single street is found and that the street contains `1037` addresses, this is probably an issue similar to https://github.com/pelias/interpolation/issues/8

**Comment by missinglink** [comment]
3x house number 1004..

```
131561142|11760710|OA|1004.0|40.7494493|-74.0312138|L|40.7494223|-74.0310659
131561143|11760710|OA|1004.0|40.7494572|-74.0312583|L|40.7494221|-74.031066
131561144|11760710|OA|1004.0|40.7494649|-74.0313022|L|40.7494218|-74.0310661
131561145|11760710|OA|1004.0|40.7494725|-74.0313459|L|40.7494215|-74.0310662
```

**Comment by missinglink** [comment]
looks like this one is a red herring ^

![ss](https://cloud.githubusercontent.com/assets/738069/19653362/8a8737b6-9a14-11e6-9c80-c7da485fb552.png)

**Comment by missinglink** [comment]
should be resolved in https://github.com/pelias/interpolation/commit/4d861bc980c4f7aacfa2604220803f992db9d12d

**Comment by missinglink** [comment]
looks better in https://github.com/pelias/interpolation/blob/master/test/functional/willow_ave/reports/preview.geojson

will do a full planet rebuild before closing.

**Comment by missinglink** [comment]
this issue is fixed in production
