### ISSUE TITLE
Mirror TIGER data

### ISSUE THREAD

**Issue by orangejulius** [pelias/interpolation#133]
[TIGER](https://www.census.gov/geo/maps-data/data/tiger.html) data for street address ranges in the United States is currently downloaded direct from the US Census FTP server. It's quite slow.

As a [government work](https://catalog.data.gov/dataset/tiger-line-shapefile-2015-2010-nation-u-s-2010-census-5-digit-zip-code-tabulation-area-zcta5-na/resource/be098b16-a303-4072-9aaf-908cbfccd519), TIGER data _should_ be public domain. Therefore we should be able to mirror it to S3 or other fast location. It might already be on there.

**Comment by kylebarron** [comment]
https://census-backup.s3.amazonaws.com/index.html

**Comment by orangejulius** [comment]
@kylebarron i knew it! thanks

**Comment by orangejulius** [comment]
oh and thanks @iandees too :)
