### ISSUE TITLE
`interpolate oa` stops with no addresses imported

### ISSUE THREAD

**Issue by kylebarron** [pelias/interpolation#135]
I downloaded all US addresses from OpenAddresses, unzipped the four files, and then appended them into a single csv file with `cat us/**/*.csv > all.csv`. But then 
```
./interpolate oa address.db street.db < all.csv
```
on master gave output of 
```
> ./interpolate oa address.db street.db < all.csv
0       0/sec
0       0/sec
0       0/sec
0       0/sec
```
and on production gave output of 
```
> ./interpolate oa address.db street.db < all.csv
0       0/sec
```

The `address.db` file is only 12KB, so not much happened.

**Comment by shanmeiliu** [comment]
@missinglink 
Hi, thanks for the explanation. I am able to populate the address.db now, however there is problem with the postcode field, even I added that in the CREATE Table statement in query/table. js and configured the stream/oa/convert.js, the postcode is null in address.db, is there a way to add postcode?

**Comment by missinglink** [comment]
Hi @shanmeiliu, glad that worked for out for you.

It would be better to open a new issue on GitHub for each new problem you're having.

I'm going to close this thread as the issue reported in the description is now solved.

If you'd like some help with postcodes could you please open a new issue explaining what you're trying to achieve.
