### ISSUE TITLE
Rebuild DB error

### ISSUE THREAD

**Issue by ibBogdan** [pelias/interpolation#136]
Hi there,

I'm trying to rebuild the database for interpolation and it's giving me this:

```
[root@pelias dockerfiles]# docker-compose run interpolation bash ./docker_build.sh
Starting pelias_libpostal_baseimage ... done

> pelias-interpolation@0.0.0-semantic-release build /code/pelias/interpolation
> ./script/build.sh

- importing polylines

npm ERR! Linux 3.10.0-229.1.2.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.13.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! pelias-interpolation@0.0.0-semantic-release build: `./script/build.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pelias-interpolation@0.0.0-semantic-release build script './script/build.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pelias-interpolation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./script/build.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pelias-interpolation
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pelias-interpolation
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /code/pelias/interpolation/npm-debug.log
```
Also if i try running 

```
[root@pelias dockerfiles]# docker-compose run interpolation bash ./interpolate osm "/opt/pelias/interpolation/address.db" "/opt/pelias/interpolation/street.db" < /opt/pbf2json/osm_data.json
Starting pelias_libpostal_baseimage ... done
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_CANTOPEN: unable to open database file
    at Error (native)
read unix @->/var/run/docker.sock: read: connection reset by peer
```

Can you help?

Thank you,
Bogdan

**Comment by ibBogdan** [comment]
[root@pelias ~]# cd /opt/pelias/interpolation/
[root@pelias interpolation]# ls
address.db  conflate_oa.err  conflate_oa.out  conflate_oa.skip  conflate_osm.err  conflate_osm.out  polyline.err  polyline.out  street.db  street.db.gz  tmp


yup.. it does..

**Comment by ibBogdan** [comment]
hmmm .. 
this doesn`t work .. 
[root@pelias dockerfiles]# docker-compose run --rm interpolation ls -lah /opt/pelias/interpolation/street.db
Starting pelias_libpostal_baseimage ... done
ls: cannot access '/opt/pelias/interpolation/street.db': No such file or directory


but 
[root@pelias dockerfiles]# stat /opt/pelias/interpolation/street.db
  File: '/opt/pelias/interpolation/street.db'
  Size: 32768           Blocks: 64         IO Block: 4096   regular file
Device: ca01h/51713d    Inode: 15207279    Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-04-23 10:29:12.245660000 +0000
Modify: 2018-04-20 07:24:33.792660000 +0000
Change: 2018-04-20 07:24:33.792660000 +0000
 Birth: -
[root@pelias dockerfiles]#
 works .. what am i missing?

**Comment by missinglink** [comment]
I think what you are missing is a link from your local filesystem in to the docker container filesystem.

The two are not linked unless you explicitly do so. For example, the content of `/tmp` on your local file will be different from `/tmp` inside the container, because it has its own distinct volume(s).

The `docker` command has the `-v` flag and the `docker-compose` command has the [volumes section](https://github.com/pelias/dockerfiles/blob/master/docker-compose.yml#L98-L101).

In the default dockerfiles setup I have set the `/data` dir inside the container to point to the directory on your local machine specified with the `DATA_DIR` env var.

So, two options, firstly you can: `export DATA_DIR=/opt/pelias/interpolation` and then when you run `docker-compose` it'll mount that for you as `/data` or you can add another `volumes` line in the `docker-compose.yml` which has any path mapping you like.

**Comment by missinglink** [comment]
Also worth noting that docker on OSX might require additional permissions to access non-default paths, you can configure this via the settings.

**Comment by ibBogdan** [comment]
cool... thank you very much. i`ll try that and come back with a reply :)

**Comment by ibBogdan** [comment]
@missinglink i managed to link the files :D yeey :)) the only thing is that rebuilding the database.. doesn`t import anything in the street.db and address.db files

also .. can you please help me with the first issue regarding the polylines?

thank you.
