### ISSUE TITLE
Timeout of 250ms exceeded

### ISSUE THREAD

**Issue by Binternet** [pelias/interpolation#147]
From the API logs:
`
[libpostal] http://localhost:8080/parse?address=%D7%9E%D7%9B%D7%9C%D7%9C%D7%AA%20%D7%A4%D7%A8%D7%A1: {"timeout":250,"code":"ECONNABORTED","errno":"ETIME","retries":3}
error: [api] [middleware:interpolation] Timeout of 250ms exceeded`

Both libpostal and interpolation are running in containers:
- libpostal > pelias/go-whosonfirst-libpostal
- interpolation > pelias/interpolation

`docker stats` shows that CPU usage as ~20% max and MEM usage is ~4GB / 32GB 
NET I/O is 59M / 2M but i'm not so sure about it since it stuck this way even when i'm not making calls to the api.

**Comment by orangejulius** [comment]
Following up from our earlier conversation :)

The libpostal one is likely a configuration issue, maybe the service is not running or listening on that port? It does take a few seconds to start up as well. However once started, the libpostal service is extremely fast. Very rarely does it take even 10ms to respond.

Interpolation is really the opposite story. It's quite slow, so the default 250ms is not good (we may consider increasing that default to 5 seconds)

**Comment by Binternet** [comment]
OK
Libpostal seems to be working great and really fast but I do get random timeout errors:

`|index    | 2018-05-23T08:39:52.145Z - error: [libpostal] http://localhost:8080/parse?address=2700%20delano: {"timeout":250,"code":"ECONNABORTED","errno":"ETIME","retries":3}
2|index    | 2018-05-23T08:39:52.146Z - warn: [api] unknown geocoding error string: Timeout of 250ms exceeded`

Libpostal is running in a container with the `pelias/go-whosonfirst-libpostal` image
And the API is running on 3 threads via [pm2](http://pm2.keymetrics.io/) process manager.

**Comment by missinglink** [comment]
can we mark this issue as resolved by https://github.com/pelias/interpolation/pull/158 ?

**Comment by Binternet** [comment]
haven't tested it (yet) but If it has passed your tests it's fine by me.
