### ISSUE TITLE
tiger download dir does not exist

### ISSUE THREAD

**Issue by jeremy-rutman** [pelias/interpolation#193]
when doing an install using the pelias docker system , `pelias prepare all` hit

```
- conflating openstreetmap
- conflating tiger
tiger download dir does not exist
```
The code for [tiger conflate](https://github.com/pelias/interpolation/blob/master/script/conflate_tiger.sh) is looking for $TIGERPATH/shapefiles ; I set the download dir for tiger in pelias.json to be other than default so maybe the line 
TIGERPATH=${TIGERPATH:-"$WORKINGDIR/data/tiger"  is not seeing the TIGERPATH  set by pelias.json

**Comment by jeremy-rutman** [comment]
If this happens after a long download process you can try to save the day (or week as it may be) , if you ave been installing using docker, by docker-running the remaining commands (remember to  link the data volume in and make sure your data vol has write permissions ) :
```
sudo chmod -R a+w  <data_dir in .env> #so docker can write
docker run -it -v <data_dir in .env>:/data pelias/interpolation /bin/bash
cd scripts ; # then run the  relevant stuff from docker_build.sh
```

**Comment by orangejulius** [comment]
Fixed in https://github.com/pelias/interpolation/pull/218
