### ISSUE TITLE
Make TIGER data optional

### ISSUE THREAD

**Issue by mihneadb** [pelias/interpolation#194]
Hi,

Following the documented steps for setting up a (non-US) country, I'm getting an error for missing TIGER data ("tiger download dir does not exist"). As discussed in other threads, this data is not available for all regions of the world, so I'm asking whether this part of the build script can be made optional.

Right now you get a nonzero return code that makes the whole process more difficult, as well as an incomplete (? not sure what the outcome is actually, didn't look into this) interpolation setup.

What are your thoughts on this?

**Comment by orangejulius** [comment]
Hey @mihneadb,
We'd definitely like to ensure non-US countries work well with the interpolation service. There was some work done in https://github.com/pelias/interpolation/pull/182 to help ensure the download can be skipped based on configuration, but I would definitely not be surprised to learn about other areas of the code that expect TIGER data to be present.

**Comment by mihneadb** [comment]
I'm talking about the [build script](https://github.com/pelias/interpolation/blob/master/script/build.sh#L60-L61) which calls conflate_tiger.sh that [exits 1](https://github.com/pelias/interpolation/blob/master/script/conflate_tiger.sh#L53-L57) if that data is not available.

If that step in the build script were optional, would everything be fine afterwards? I could make a PR with that change if it makes sense to you.

**Comment by arne-cl** [comment]
I would also appreciate if this could be made optional (e.g. via an ENV like ``TIGER_REQUIRED=false``)
and would volunteer to implement it.

As a workaround, one can create an empty `data/tiger/shapefiles` directory to make this work.
For example, if you call the build script like this:

```
WORKINGDIR=/tmp/workingdir script/build.sh
```

you need to create this directory to get rid of the error:

```mkdir -p /tmp/workingdir/data/tiger/shapefiles```

**Comment by orangejulius** [comment]
Ah, thanks for flagging this again @arne-cl.

I agree, no reason we can't do a `mkdir -p` in place of [these lines](https://github.com/pelias/interpolation/blob/60633a0a3524b96e9dea1d519952eee23ca2bcb5/script/conflate_tiger.sh#L53-L57) in `conflate_tiger.sh`. PR welcome :)

**Comment by orangejulius** [comment]
It's funny. We do the right thing [just a few lines earlier](https://github.com/pelias/interpolation/blob/master/script/conflate_tiger.sh#L46-L47) for a tmpdir. 🤷‍♂
