### ISSUE TITLE
could not locate bindings file

### ISSUE THREAD

**Issue by pravink** [pelias/interpolation#226]
Hey team! 

I am trying to build the street db and address db using 
./interpolate polyline street.db < /efs/data/polyline/new_zealand.0sv
but i m getting below error-
`/efs/pelias-code/interpolation/node_modules/bindings/bindings.js:135
  throw err;
  ^
Error: Could not locate the bindings file. Tried:
 → /efs/pelias-code/interpolation/node_modules/node-postal/build/expand.node`

does anyone knows how to get over this issue?

I did tried reinstalling npm modules but it fails.

thanks!

**Comment by missinglink** [comment]
Please add information about your system, node version etc.

**Comment by pravink** [comment]
Hi @missinglink Thanks for your reply. 

I am running this on AWS ec2 instance with node v13.x 

later I did trying downgrading the node version to V10.x and it worked. In addition to that I also had to set LD_LIBRARY_PATH `export   LD_LIBRARY_PATH=/usr/local/lib`
And it worked well.

Thanks for your reply again! you can close this issue.
