### ISSUE TITLE
total openaddresses records imported in address.db is only 56000 for AUS

### ISSUE THREAD

**Issue by pravink** [pelias/interpolation#231]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

I have prepared the street.db - 7.7GB successfully for the whole planet.
imported openaddresses into address.db for AU only - 

- adds 56000 records 

- skipped 2904 records
- sample of skipped records 
`889 {"id":"/efs/data/openaddresses/countrywide/oa/au/countrywide:7ad4921138042f53","source":"OA","coords":{"def   2889 ault":{"lon":150.6961154,"lat":-35.1490922,"dist":0}},"number":"74","street":"ADAMS CLOSE","unit":null,"cit   2889 y":"JERVIS BAY","district":null,"region":"OT","postcode":"2540"}
   2890 {"id":"/efs/data/openaddresses/countrywide/oa/au/countrywide:ed633e1bb87c7815","source":"OA","coords":{"def   2890 ault":{"lon":150.6961154,"lat":-35.1490922,"dist":0}},"number":"75","street":"ADAMS CLOSE","unit":null,"cit   2890 y":"JERVIS BAY","district":null,"region":"OT","postcode":"2540"}
   2891 {"id":"/efs/data/openaddresses/countrywide/oa/au/countrywide:8869a411d8a88084","source":"OA","coords":{"def   2891 ault":{"lon":150.6961154,"lat":-35.1490922,"dist":0}},"number":"77","street":"ADAMS CLOSE","unit":null,"cit   2891 y":"JERVIS BAY","district":null,"region":"OT","postcode":"2540"}`

- and only 28 are  failed with "could not reliably parse housenumber 44-44A" errrors

I am suspecting the number of records for Australia [56000] is a very small compared to NZ records [196000] which I have imported successfully.

Is the Australia openaddresses count correct? or did i am missing something while import.

Thanks,
Pravin!

---
#### Here's what I did :innocent:

---
#### Here's what I got :scream_cat:

---
#### Here's what I was expecting :sparkles:

---

**Comment by pravink** [comment]
More information-
NZ openaddresses csv has - 2065777 records
AU openaddresses csv has - 14718219 records

let me know if any other information is required..

thanks again!

**Comment by missinglink** [comment]
Hi @pravink, these sort of questions are not a great fit for the issue tracker, which is for reporting known bugs.
We're a small core team and we'll likely not have time to provide hands-on support for your builds on a volunteer basis.

For commercial support reach out to https://geocode.earth/
