### ISSUE TITLE
Update package.json to address security vulnerabilities of dependency libraries

### ISSUE THREAD

**Issue by sugiantoaudi** [pelias/interpolation#233]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I think could be improved :trophy:
**Source:** https://github.com/pelias/interpolation/blob/master/package.json
**Vulnerable module**: fstream
**Current version**: 0.1.11
**Recommendation**: fstream, update to version 1.0.12 or latest to address Arbitrary File Overwrite issue (https://app.snyk.io/vuln/SNYK-JS-FSTREAM-174725)

**Comment by missinglink** [comment]
Hi @sugiantoaudi, we do not directly require the `fstream` module, can you please say more about the dependency tree.

**Comment by loadit1** [comment]
@missinglink let me answer :) 
fstream is used by unzip package which is not active maintaned anymore. Replacement can be package [unzipper](https://www.npmjs.com/package/unzipper) with similar behaviour

**Comment by orangejulius** [comment]
I had a chance to put in a quick PR to move us over to `unzipper`. Thanks @sugiantoaudi for the report and @loadit1 for the diagnosis and recommendation
