### ISSUE TITLE
Street Address Interpolation - Interactive Demo - PAGE NOT FOUND

### ISSUE THREAD

**Issue by rajeshchittorsundaram** [pelias/interpolation#266]
I am trying to understand the specifics of the algorithm that performs a street address interpolation 
https://www.mapzen.com/blog/interpolation/
When I click on the 'INTERACTIVE DEMO' in this page, I get an error "Can't reach this page" (Target: http://geo.wiz.co.nz/projection.html)
Can you please let me know how to access the interactive demo ?

**Comment by missinglink** [comment]
Hi @rajeshchittorsundaram, the correct link is https://interpolation.demo.geocode.earth

I'll open another issue to fix the referral, thanks!
