### ISSUE TITLE
Data loaded with the csv-import module is not used on the interpolation module

### ISSUE THREAD

**Issue by irbian** [pelias/interpolation#284]
**Describe the bug**
Data loaded with the csv-import module is not used on the interpolation module

**Steps to Reproduce**
Follow https://github.com/pelias/docker tutorial
Import a CSV with address and import it with pelias import csv
Run a pelias preparate interpolation

**Expected behavior**
I expect the interpolation module to check on the elasticsearch database and not only on the openaddress and openstreetmap and/or the whatever custom importer you create

**Comment by orangejulius** [comment]
Hey @irbian,

Yeah, you're correct, this isn't supported right now, and I see how it can be a little confusing.

The interpolation engine and Elasticsearch are completely separate, and don't talk to each other at all. The csv-importer (and all the other importers) are concerned only with bringing data into Elasticsearch.

Further, the interpolation engine doesn't really support custom data like the csv-importer is designed to handle. That said, the OpenAddresses CSV format supported by the interpolation engine is simple enough that you can probably easily convert your data to something the interpolation engine can read. And I think if you copy the CSV to the openaddresses data directory, the interpolation engine will pick it up automatically during `pelias prepare interpolation`.

Supporting this out of the box is probably not something the pelias/docker setup can support: it's really designed to handle the most common cases and we don't want to make it more complex by supporting every possible workflow. But it should be something you can handle yourself.

Let us know how it goes!

**Comment by irbian** [comment]
Thanks for your input

Tbh I expected the interpolation module to consume the elasticsearch, the same as other modules. Do other modules **not** use the elastic search?

I understand then that the interpolation module is... "standalone" so if I want to reuse the street and address datasets loaded into the elasticsearch I´ll have to convert them to openaddress/openstreet so the module can work

**Comment by orangejulius** [comment]
Actually nothing talks to Elasticsearch except the importers and the Pelias [API](https://github.com/pelias/api). All the other services are completely independent. They do sometimes _use_ the same data source, but in a completely different way. For example the interpolation service stores address information from OpenAddresses in a sqlite database, whereas the openaddresses importer stores it in Elasticsearch.

This image from the main Pelias repo is meant to explain that, hopefully it's at least somewhat effective. 🤣 

![image](https://user-images.githubusercontent.com/111716/144726046-4c762c78-3046-4116-8ef4-97ea4f07c0a2.png)

So yes, if you take your custom data that you imported to Elasticsearch with the `csv-importer`, and convert it to the OpenAddresses (NOT OpenStreetMap, that's completely different :) ) format, it should work.

The OpenAddresses CSV format is very simple, here's a simple example with one row:

|LON|LAT|NUMBER|STREET|UNIT|CITY|DISTRICT|REGION|POSTCODE|ID|HASH|
| --- | --- | --- | --- | --- | --- | ---| --- | --- | --- | --- |
|-123.0240369|44.8532685|123|Some St||SALEM|MARION||97301|121|0ad6784ce068164a|

You can even skip the ID and HASH columns. The hash is ignored and the ID can be re-generated from the row number if it's missing.

**Comment by irbian** [comment]
Hey, thanks for your input. Think on my questions as that of a newbie on pelias

> All the other services are completely independent.

So if I have a custom dataset I´ll need to prepare it to each service I want to use in. Is this intended or is planned to move them to elastic eventually?

> So yes, if you take your custom data that you imported to Elasticsearch with the csv-importer, and convert it to the OpenAddresses (NOT OpenStreetMap, that's completely different :) ) format, it should work.

Actually yes, I indeed make it work but it was surprising to need a two different process

**Comment by irbian** [comment]
I still would like some input on this if it's possible
