### ISSUE TITLE
nearest street - max distance

### ISSUE THREAD

**Issue by missinglink** [pelias/interpolation#51]
currently the nearest street API does not have a max distance value, so it will return *all* streets whose MBR intersects the input point.

this can result in very large, yet distant roads being returned, such as in this example: http://interpolation.wiz.co.nz/street/near/geojson?lat=40.74429825919934&lon=-73.9896583557129 where the `brooklynqueens expressway` is returned.

adding a `max_distance` parameter would decrease the amount of results returned and, as a result, would speed up serving and parsing.

**Comment by dianashk** [comment]
How urgent would you say this issue is? Also how much work do you estimate it to be? Thanks, @missinglink.

**Comment by missinglink** [comment]
it's already complete, there is a PR https://github.com/pelias/interpolation/pull/52
