### ISSUE TITLE
Floating point precision may be causing test failures

### ISSUE THREAD

**Issue by orangejulius** [pelias/interpolation#59]
https://travis-ci.org/pelias/interpolation/jobs/226891165

```
 ✖ should be equivalent

    -----------------------

      operator: deepEqual

      expected: |-

        [ '5|1|TIGER|208773790|1.0|46.534084|-110.908557|L|46.5340609148833|-110.908556832798', '6|1|TIGER|208773790|99.0|46.534063|-110.910854|L|46.5340530413783|-110.910853927871', '3|1|TIGER|263702490|100.0|46.533874|-110.934964|R|46.5338750002214|-110.934964011328', '4|1|TIGER|208773717|101.0|46.533874|-110.934964|R|46.5338750002214|-110.934964011328', '8|1|VERTEX||117.653||||46.533863|-110.937203', '7|1|VERTEX||125.049||||46.533851|-110.938141', '1|1|TIGER|263702490|198.0|46.53376|-110.94752|R|46.5337752241147|-110.947520259902', '2|1|TIGER|208773717|199.0|46.53376|-110.94752|R|46.5337752241147|-110.947520259902' ]

      actual: |-

        [ '5|1|TIGER|208773790|1.0|46.534084|-110.90856|L|46.5340609046008|-110.908559832723', '6|1|TIGER|208773790|99.0|46.53406|-110.91085|L|46.5340530550139|-110.910849949699', '3|1|TIGER|263702490|100.0|46.53387|-110.93496|R|46.5338750214159|-110.93496005687', '4|1|TIGER|208773717|101.0|46.53387|-110.93496|R|46.5338750214159|-110.93496005687', '8|1|VERTEX||117.678||||46.533863|-110.937203', '7|1|VERTEX||125.072||||46.533851|-110.938141', '1|1|TIGER|263702490|198.0|46.53376|-110.94752|R|46.5337752241147|-110.947520259902', '2|1|TIGER|208773717|199.0|46.53376|-110.94752|R|46.5337752241147|-110.947520259902' ]

      at: Test.<anonymous> (/home/travis/build/pelias/interpolation/test/functional/cemetery_rd/run.js:107:7)
```

If we can help fix this with some tasteful rounding, that would be great.

**Comment by orangejulius** [comment]
If I remember correctly, these errors go away with a newer version of gdal than the one installed in Travis images.

**Comment by missinglink** [comment]
almost... I believe that when `libproj` is available on the system then `gdal` uses that, otherwise it uses some internal projection algorithms, this is why the calculations are similar but not exactly the same.

could you add an explicit `apt-get` for the library you installed? I don't think it's a problem with `FROM ubuntu:16.04` but it's an issue on the ancient Travis ubuntu images.

**Comment by missinglink** [comment]
this issue should have been resolved in https://github.com/pelias/interpolation/pull/157

**Comment by orangejulius** [comment]
I recall that we actually fixed this a long time ago by installing the proper version of dependencies on Travis. We had to enable `sudo` mode on Travis, which is much slower, and spend time installing packages and their deps.

If you think that's no longer needed it would be worthwhile to test if we can remove that code and have faster CI runs again.
