### ISSUE TITLE
Include "Configuration" section in README

### ISSUE THREAD

**Issue by tigerlily-he** [pelias/interpolation#70]
Show sample ~/pelias.json configuration file for how to connect interpolation service to the API

**Comment by orangejulius** [comment]
We should definitely mention that the interpolation service is meant to be used with the API (although it can also stand on its own, which I think is already made clear in the README). There are [instructions for connecting services](https://github.com/pelias/api/#pelias-config) in the API README already, perhaps we can link there to avoid having the same docs twice.

**Comment by orangejulius** [comment]
We should definitely mention that the interpolation service is meant to be used with the API (although it can also stand on its own, which I think is already made clear in the README). There are [instructions for connecting services](https://github.com/pelias/api/#pelias-config) in the API README already, perhaps we can link there to avoid having the same docs twice.
