### ISSUE TITLE
Detect OS and use appropriate PBF2JSON build

### ISSUE THREAD

**Issue by dianashk** [pelias/interpolation#73]
In the build script, the following line should be changed to use the build that corresponds to the host operating system.

```bash
PBF2JSON_BIN=${PBF2JSON_BIN:-"$DIR/../node_modules/pbf2json/build/pbf2json.linux-x64"};
```

See #72 for original comment

**Comment by missinglink** [comment]
resolved in https://github.com/pelias/interpolation/pull/214
